### ISSUE TITLE
JSONDecodeError if I try running the action

### ISSUE THREAD

**Issue by drademacher** [k2bd/advent-readme-stars#20]
Hello, I encountered an issue in my repository
The code: https://github.com/drademacher/advent_of_rust/blob/main/.github/workflows/readme-stars.yml
The run: https://github.com/drademacher/advent_of_rust/actions/runs/8302930402

Stacktrace:

> /usr/bin/docker run --name c7eb843890a215d44cafaf86b248ab89916d_4f357d --label 96c7eb --workdir /github/workspace --rm -e "INPUT_USERID" -e "INPUT_SESSIONCOOKIE" -e "INPUT_YEAR" -e "INPUT_LEADERBOARDID" -e "INPUT_TABLEMARKER" -e "INPUT_STARSYMBOL" -e "INPUT_HEADERPREFIX" -e "INPUT_READMELOCATION" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/advent_of_rust/advent_of_rust":"/github/workspace" 96c7eb:843890a215d44cafaf86b248ab89916d
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 971, in json
>     return complexjson.loads(self.text, **kwargs)
>   File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
>     return _default_decoder.decode(s)
>   File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
>     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
>   File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
>     raise JSONDecodeError("Expecting value", s, err.value) from None
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/runpy.py", line [19](https://github.com/drademacher/advent_of_rust/actions/runs/8302930402/job/22726157476#step:4:20)7, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "/advent_readme_stars/__main__.py", line 8, in <module>
>     edited = update_readme(lines)
>   File "/advent_readme_stars/update.py", line 70, in update_readme
>     new_readme = insert_table(reduced)
>   File "/advent_readme_stars/update.py", line 53, in insert_table
>     stars_info = sorted(list(get_progress()), key=lambda p: p.day)
>   File "/advent_readme_stars/progress.py", line [20](https://github.com/drademacher/advent_of_rust/actions/runs/8302930402/job/22726157476#step:4:21), in get_progress
>     leaderboard_info = res.json()
>   File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 975, in json
>     raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
> requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by drademacher** [comment]
I had not created a private leaderboard before hand. The error was not clear for me from stacktrace. If you don't plan to use a leaderboard you will miss this info when reading the guide.
