### ISSUE TITLE
Action keeps failing in `docker run`

### ISSUE THREAD

**Issue by haphaeu** [k2bd/advent-readme-stars#25]
The [action run](https://github.com/haphaeu/advent-of-code-rust-2024/actions/runs/12204312334/job/34049128676) in my repo keeps failing at the step `Run k2bd/advent-readme-stars@v1`, right after `docker run` with some sort of JSON error: `requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

Failed action step:
```

Run k2bd/advent-readme-stars@v1
  with:
    userId: ***
    sessionCookie: ***
    year: ***
    tableMarker: <!--- advent_readme_stars table --->
    starSymbol: ⭐
    headerPrefix: ##
    readmeLocation: README.md
/usr/bin/docker run --name a1163c65bf18449604cb49c46057d48149df4_61194c --label 8a1163 --workdir /github/workspace --rm -e "INPUT_USERID" -e "INPUT_SESSIONCOOKIE" -e "INPUT_YEAR" -e "INPUT_LEADERBOARDID" -e "INPUT_TABLEMARKER" -e "INPUT_STARSYMBOL" -e "INPUT_HEADERPREFIX" -e "INPUT_READMELOCATION" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_ENVIRONMENT" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e "ACTIONS_RESULTS_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/advent-of-code-rust-***/advent-of-code-rust-***":"/github/workspace" 8a1163:c65bf18449604cb49c46057d48149df4
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.9/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.9/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.9/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/advent_readme_stars/__main__.py", line 8, in <module>
    edited = update_readme(lines)
  File "/advent_readme_stars/update.py", line 70, in update_readme
    new_readme = insert_table(reduced)
  File "/advent_readme_stars/update.py", line 53, in insert_table
    stars_info = sorted(list(get_progress()), key=lambda p: p.day)
  File "/advent_readme_stars/progress.py", line [2](https://github.com/haphaeu/advent-of-code-rust-2024/actions/runs/12204312334/job/34049128676#step:4:2)0, in get_progress
    leaderboard_info = res.json()
  File "/usr/local/lib/python[3](https://github.com/haphaeu/advent-of-code-rust-2024/actions/runs/12204312334/job/34049128676#step:4:3).9/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

**Comment by kovyrin** [comment]
Had the same issue and after some debugging traced it to the fact that I did no have my private leaderboard created. After creating one, it all worked as expected.

**Comment by haphaeu** [comment]
Sweet. Indeed I was part of someone else's private leaderboard. Didn't read the instructions carefully. After creating my own the action run throught. Thanks!
